#!/usr/bin/env bash
# changelog-gen.sh — 从 git 历史自动生成 CHANGELOG.md
#
# 用法: bash changelog-gen.sh [since_tag] [output_file]
#   since_tag: 起始 tag（默认最近一个 tag）
#   output_file: 输出文件（默认 ./CHANGELOG.md）

set -euo pipefail

# ── 参数 ──
SINCE_TAG="${1:-$(git describe --tags --abbrev=0 2>/dev/null || echo '')}"
OUTPUT="${2:-CHANGELOG.md}"
REPO_URL=$(git config --get remote.origin.url 2>/dev/null | sed 's/\.git$//' || echo "")

# ── 1. 如果没传 tag，列出现有 tags 让用户选 ──
if [ -z "$SINCE_TAG" ]; then
  TAGS=$(git tag --sort=-creatordate 2>/dev/null)
  if [ -n "$TAGS" ]; then
    echo "📋 已有的 tags:"
    echo "$TAGS" | head -10
    echo ""
    SINCE_TAG=$(echo "$TAGS" | head -1)
  else
    # 没有 tag，取第一个 commit
    SINCE_TAG=$(git rev-list --max-parents=0 HEAD 2>/dev/null || echo "HEAD~100")
  fi
fi

# ── 2. 获取当前版本信息 ──
CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
if [ -z "$(git tag 2>/dev/null)" ]; then
  CURRENT_VERSION="Unreleased"
fi

TODAY=$(date +%Y-%m-%d)

echo "🔍 扫描 $SINCE_TAG..HEAD 之间的 commits..."

# ── 3. 收集 commits（从 SINCE_TAG 到 HEAD） ──
COMMITS=$(git log "$SINCE_TAG"..HEAD --pretty=format:"%s" 2>/dev/null || git log --pretty=format:"%s")

if [ -z "$COMMITS" ]; then
  echo "⚠️  $SINCE_TAG..HEAD 之间没有新 commit"
  exit 0
fi

# ── 4. 分类函数 ──
declare -a ADDED=()
declare -a FIXED=()
declare -a CHANGED=()
declare -a REMOVED=()
declare -a OTHER=()

categorize() {
  local msg="$1"
  # 转小写方便匹配
  local lower=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

  if echo "$lower" | grep -qE '^(add|feat|new|implement|introduce|create|support)'; then
    ADDED+=("$msg")
  elif echo "$lower" | grep -qE '^(fix|bug|patch|hotfix|resolve|repair|correct)'; then
    FIXED+=("$msg")
  elif echo "$lower" | grep -qE '^(remove|delete|drop|deprecate|clean)'; then
    REMOVED+=("$msg")
  elif echo "$lower" | grep -qE '^(change|update|modify|refactor|improve|enhance|tweak|adjust|optimize|upgrade)'; then
    CHANGED+=("$msg")
  else
    # 兜底：检查关键词
    if echo "$lower" | grep -qE '(add|feat|new feature|implement)'; then
      ADDED+=("$msg")
    elif echo "$lower" | grep -qE '(fix|bug|patch|hotfix)'; then
      FIXED+=("$msg")
    elif echo "$lower" | grep -qE '(remove|delete|drop|deprecat)'; then
      REMOVED+=("$msg")
    else
      CHANGED+=("$msg")
    fi
  fi
}

# ── 5. 逐条分类 ──
while IFS= read -r line; do
  [ -z "$line" ] && continue
  # 跳过 merge commit
  [[ "$line" =~ ^Merge ]] && continue
  categorize "$line"
done <<< "$COMMITS"

# ── 6. 生成 CHANGELOG ──
{
  echo "# Changelog"
  echo ""
  echo "## [$CURRENT_VERSION] - $TODAY"
  echo ""

  if [ ${#ADDED[@]} -gt 0 ]; then
    echo "### Added"
    for item in "${ADDED[@]}"; do
      echo "- $item"
    done
    echo ""
  fi

  if [ ${#FIXED[@]} -gt 0 ]; then
    echo "### Fixed"
    for item in "${FIXED[@]}"; do
      echo "- $item"
    done
    echo ""
  fi

  if [ ${#CHANGED[@]} -gt 0 ]; then
    echo "### Changed"
    for item in "${CHANGED[@]}"; do
      echo "- $item"
    done
    echo ""
  fi

  if [ ${#REMOVED[@]} -gt 0 ]; then
    echo "### Removed"
    for item in "${REMOVED[@]}"; do
      echo "- $item"
    done
    echo ""
  fi

  # ── 统计 ──
  echo "---"
  echo ""
  echo "> 🤖 Generated by changelog-gen — ${#ADDED[@]} added, ${#FIXED[@]} fixed, ${#CHANGED[@]} changed, ${#REMOVED[@]} removed"
} > "$OUTPUT"

echo ""
echo "✅ CHANGELOG 已生成: $OUTPUT"
echo "   📦 Added:   ${#ADDED[@]}"
echo "   🐛 Fixed:   ${#FIXED[@]}"
echo "   🔧 Changed: ${#CHANGED[@]}"
echo "   🗑️  Removed: ${#REMOVED[@]}"
